definitions_version = 1

[[theme]]
name = "master-pywal-theme"
repository = "https://github.com/AnthonyMichaelTDM/master-pywal-theme/"
commit = "*"
version = "2.0.0"
leftwm_versions = "*"

[[theme]]
name = "mpt-tablet"
repository = "https://github.com/AnthonyMichaelTDM/mpt-tablet/"
commit = "*"
version = "2.0.0"
leftwm_versions = "*"

